replicaCount: 10

image:
  repository: gcr.io/p8pigsol/nodejs-test
  tag: latest
  pullPolicy: Always

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

updateStrategy:
  type: RollingUpdate
  maxUnavailable: 3

containerPort: 3000

service:
  type: LoadBalancer
  port: 3000

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

## Horizontal Pod Scaling
hpa:
  maxReplicas: 20
  minReplicas: 10
  avgCPU: 50
  avgMemory: 60

## For Kubernetes 1.16 and before, "system-cluster-critical" and "system-node-critical" classnames,
## are limited to the "kube-system" namespace.
## There is no need to create this if Kubernetes version is 1.17 (or higher)
createPriorityClass: true  # If set to false, highest system defined priority "system-node-critical" is used
podPriority:
  description: For pods with highest user defined priority
  value: 1000000000 # Maximum allowed value of a user defined priority
  globalDefault: false
