apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "insider.fullname" . }}
  labels:
{{ include "insider.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "insider.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  strategy:
    type: {{ .Values.updateStrategy.type }}
    rollingUpdate:
      maxUnavailable: {{ .Values.updateStrategy.maxUnavailable }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "insider.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      {{- if .Values.imageCredentials.create }}
      imagePullSecrets:
      - name: {{ include "insider.fullname" . }}
      {{- else }}
      {{- with .Values.externalImagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- end }}

      {{- if .Values.supportsDefaultClass }}
      priorityClassName: system-node-critical
      {{- else }}
      priorityClassName: {{ include "insider.fullname" . }}
      {{- end }}

      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.containerPort }}
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
