apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "insider.fullname" . }}
  labels:
{{ include "insider.labels" . | indent 4 }}
spec:
  maxReplicas: {{ .Values.hpa.maxReplicas }}
  minReplicas: {{ .Values.hpa.minReplicas }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "insider.fullname" . }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: {{ .Values.hpa.avgCPU }}
  - type: Resource
    resource:
      name: memory
      targetAverageUtilization: {{ .Values.hpa.avgMemory }}
