## In Kubernetes version 1.16 and below pre-defined priorityClassNames, are only affective in "kube-system" namespace.
## For other namespaces, use custom priorityClass. This isn't needed for k8s version 1.17 and above
{{- if .Values.createPriorityClass }}
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: {{ include "insider.fullname" . }}
  labels:
{{ include "insider.labels" . | indent 4 }}
value: {{ .Values.podPriority.value  }}
globalDefault: {{ .Values.podPriority.globalDefault  }}
description: {{ .Values.podPriority.description  }}
{{- end }}
