## Kubernetes version 1.16 (and below) support pre-defined priority-classes "ONLY" in kube-system namespace
## For other namespaces, use custom priorityClass. This isn't needed for k8s version 1.17 and above
{{- if ne .Values.supportsDefaultClass true }}
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: {{ include "insider.fullname" . }}
  labels:
{{ include "insider.labels" . | indent 4 }}
value: {{ .Values.podPriority.value  }}
globalDefault: {{ .Values.podPriority.globalDefault  }}
description: {{ .Values.podPriority.description  }}
{{- end }}
