apiVersion: v1
kind: Service
metadata:
  name: {{ include "insider.fullname" . }}
  labels:
{{ include "insider.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: client
  selector:
    app.kubernetes.io/name: {{ include "insider.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
