apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  labels:
    app.kubernetes.io/instance: paytm
    app.kubernetes.io/name: insider
  name: paytm-insider
  namespace: default
spec:
  maxReplicas: 20
  minReplicas: 10
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: paytm-insider
  metrics:
    - type: Resource
      resource:
        name: memory
        targetAverageUtilization: 60
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 50
